// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAORjzRh1c0uFzf6yDgzUJOWIJ_Wy2PZZE',
    appId: '1:835491908057:web:80faf042caddb8d9a731c8',
    messagingSenderId: '835491908057',
    projectId: 'sotim-c1f17',
    authDomain: 'sotim-c1f17.firebaseapp.com',
    storageBucket: 'sotim-c1f17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTBNyWAkuG0dG2K6BjiHOPcLy8U3WHbsU',
    appId: '1:835491908057:android:0ad0bc3fcac93815a731c8',
    messagingSenderId: '835491908057',
    projectId: 'sotim-c1f17',
    storageBucket: 'sotim-c1f17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBHKHA1ZR4-BpWiTzWnOdqUbuZdIiw9so',
    appId: '1:835491908057:ios:edb6d64d49233e98a731c8',
    messagingSenderId: '835491908057',
    projectId: 'sotim-c1f17',
    storageBucket: 'sotim-c1f17.appspot.com',
    iosBundleId: 'com.example.tao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBHKHA1ZR4-BpWiTzWnOdqUbuZdIiw9so',
    appId: '1:835491908057:ios:63ed576d6ab3e5eea731c8',
    messagingSenderId: '835491908057',
    projectId: 'sotim-c1f17',
    storageBucket: 'sotim-c1f17.appspot.com',
    iosBundleId: 'com.example.tao.RunnerTests',
  );
}
